---
title: Live coverage
date: '`r strftime(Sys.time(), format = "%B %d, %Y")`'
output:
  html_document:
    theme: dark
    toc: False
    toc_depth: 2
#params:
#  path:
#    value: x
#  region_file:
#    value: x
#  threshold:
#    value: x
#  maxDepth:
#    value: x
#  samplesheet:
#    value: x

---

<style type="text/css">
.main-container {
  max-width: 100% !important;
  margin: auto;
}
</style>

```{r echo=F, message=F, warning=F}
# A function that returns a new table number for each run
tableno_var = 0
tableno = function() {
    tableno_var <<- tableno_var + 1
    tableno_var
}
```
```{r, include = FALSE}
knitr::opts_chunk$set(
      echo    = FALSE
    , warning = FALSE
    , message = FALSE
)
# Load required libraries
if (!require("tidyverse")) {
install.packages("tidyverse") }
if (!require("RColorBrewer")) {
install.packages("RColorBrewer") }
if (!require("cowplot")) {
install.packages("cowplot") }
if (!require("ggthemes")) {
install.packages("ggthemes") }
if (!require("kableExtra")) {
install.packages("kableExtra") }
plot_regions = FALSE

# ## Pull in the data
#if (!params$region_file == "NA") {
#  plot_regions = TRUE
#  regions = read.table(params$region_file, header=FALSE)
#}


#samplesheet = read.table(params$samplesheet, header=TRUE, sep = "\t")

#files = list.files(paste0(params$path,"/"), pattern=".depth", all.files=FALSE, full.names=TRUE)
#if (!params$threshold == "NA") {
#  threshold = params$threshold
#} else  {
#  threshold <- 30
#}
#if (!params$maxDepth == "NA") {
#  maxDepth = params$maxDepth
#} else  {
#  maxDepth <- 400
#}
files = list.files(paste0("/Users/admin1/Documents/KMA_AUH/CoverMon/CoverMon_CMV_CoverMon_reference/"), pattern=".depth", all.files=FALSE, full.names=TRUE)

regions = read.table("/Users/admin1/Documents/KMA_AUH/CoverMon/panel_files/CMV_CoverMon_reference_amplicons.bed", header=FALSE)
samplesheet = read.table("/Users/admin1/Documents/KMA_AUH/CoverMon/sample_sheet_given.tsv", header=TRUE, sep = "\t")
threshold <- 100
plot_regions = TRUE
maxDepth <- 5000

```


```{r, fig.show='hide'}
myColors <- brewer.pal(10,"Paired")
dat <- data.frame(x=runif(10),y=runif(10),
                  color_grp = as.character(rep(1:10,each = 1)), stringsAsFactors=T)
names(myColors) <- levels(dat$color_grp)
plot_cov <- function(file) { 
  dir <- str_split(file, "/")[[1]]
  barcode <- sub(".depth", "", as.character(dir[length(dir)]))
  
  cvg <- read.table(file,header=FALSE)
  
  colnames(cvg) = c("Contig","Pos","Coverage")
  
  mean_cov <- mean(cvg$Coverage)
  mean_cov <- round(mean_cov, digits=2)
  percent_over_threshold <- (nrow(cvg[cvg$Coverage >= threshold,])/nrow(cvg))*100
  percent_over_threshold <- round(percent_over_threshold, digits=2)
  cvg$Coverage[cvg$Coverage > maxDepth] <- maxDepth 
  large_contigs <- cvg %>% group_by(Contig) %>% count() %>% filter(n >= 1000) %>%   pull(Contig)
  
  filtered <- cvg %>% filter(Contig %in% large_contigs)
  
  filtered <- cvg %>% mutate(contig_nr = as.numeric(factor(Contig))) %>% mutate(idx = row_number(), color_grp = contig_nr %% 9)
  filtered <- filtered %>% mutate(color_grp = as.character(ifelse(color_grp==5,10, color_grp)))
  reduced <- filtered %>%  slice(which(Pos %% 10 == 0))
 
  plt <- ggplot(reduced,aes(x=idx, y=Coverage,color = color_grp,"5"), show.legend=FALSE)+
    geom_line(aes(group=Contig), show.legend=FALSE) + 
    geom_hline(aes(yintercept = threshold), color="darkred", show.legend=FALSE) +
    ylim(0,maxDepth) + 
    labs(title=barcode,x="Position",y="Coverage",linetype="Cutoff") +
    theme_solarized(light = FALSE) + 
    theme(title=element_text(size=24, color="lightgrey"),axis.text=element_text(size=20, color="lightgrey"),
        axis.title=element_text(size=22,face="bold"))+
    scale_color_manual(values = myColors)
  if (plot_regions== TRUE) { 
    regions <- regions[,1:3]
    colnames(regions) = c("chr","start","stop")
    
    regions <- regions %>%
         group_by(chr) %>%
         mutate(dodge = row_number()) 
    regions <- regions %>%
      left_join(filtered %>% select(Contig, color_grp) %>% distinct(), by = c("chr" = "Contig")) %>%
      mutate(color_grp = as.character(color_grp)) # Align colors with filtered
    idx_start = inner_join(regions, filtered, by=c("chr"="Contig", "start"="Pos"))
    regions$idx_start <- idx_start$idx
    idx_stop = inner_join(regions, filtered, by=c("chr"="Contig", "stop"="Pos"))
    regions$idx_stop <- idx_stop$idx
    regions <- regions %>% 
      ungroup() %>% 
      mutate(region_label = row_number())


    hotspotplot <- ggplot(regions, aes(xmin = idx_start, ymin = 0 + dodge %% 2, 
                                           xmax = idx_stop, ymax = 1 + dodge %% 2, 
                                           fill = color_grp)) +
            xlim(min(reduced$idx), max(reduced$idx)) +
            xlab("Region") +
            geom_rect(alpha = 0.5) +
            geom_text(aes(x = (idx_start + idx_stop) / 2, y = 0.5 + dodge %% 2, label = region_label), 
              color = "white", size = 5, vjust = 0.5, hjust = 0.5) +
            theme_solarized(light = FALSE) +
            theme(
                legend.position = "none",
                axis.text.y = element_blank(),
                axis.ticks.y = element_blank(),
                axis.ticks.x = element_blank()
            ) +
            scale_fill_manual(values = myColors)
        
        plt <- plot_grid(plt, hotspotplot, ncol = 1, align = "v", axis = "lr", rel_heights = c(4, 1))
    }
  
  return(list(plt,barcode,mean_cov,percent_over_threshold))
}
plots <- c()
barcodes <- c()
mean_covs <- c()
percent_over_thresholds <- c()


for(f in files) {
  sample_data <- plot_cov(f)
  plots <- append(plots, sample_data[1])
  barcodes <- append(barcodes, sample_data[2])
  mean_covs <- append(mean_covs, sample_data[3])
  percent_over_thresholds <- append(percent_over_thresholds, sample_data[4])
}
```
*Tabel `r tableno()`: Samples with insufficient coverage.*

```{r echo=F, message=F, warning=F}
summary_df <- data.frame(cbind(barcodes, mean_covs, percent_over_thresholds))

names(summary_df) <- c("Barcode", "Mean coverage", "percent_over_threshold")
#paste0("Percent over ",as.character(threshold),"x")
summary_df <- summary_df %>%  
    mutate(Barcode = as.character(Barcode))

samplesheet <- samplesheet %>%  
    mutate(barcode = as.character(barcode))

full_table <- full_join(summary_df, samplesheet, by=c("Barcode"="barcode")) %>% replace(.=="NULL", 0)
below_qc_table <- full_table[ which(full_table$percent_over_threshold < 90), ]

colnames(below_qc_table)[3] <- paste0("% positions > ",as.character(threshold),"x")
below_qc_table <- below_qc_table[order(below_qc_table$Barcode),]
below_qc_table %>%
  kbl(row.names=FALSE) %>%
  kable_styling(bootstrap_options = c("striped","bordered"))

```

*Coverage figures. Multiple contigs are displayed in alternating colours*
```{r, fig.width=30, fig.height=5, fig.keep = 'all'}
for(plt in plots) {
  plot(plt)
}
```
*Tabel `r tableno()`: Staticstics all samples.*
```{r, fig.width=30, fig.height=5, fig.keep = 'all'}
colnames(full_table)[3] <- paste0("% positions > ",as.character(threshold),"x")
full_table <- full_table[order(full_table$Barcode),]
full_table %>%
  kbl(row.names=FALSE) %>%
  kable_styling(bootstrap_options = c("striped","bordered"))
```
